In [1]:
import pandas as pd 
import numpy as np

In [2]:
df_book=pd.read_csv('data/raw/Books.csv')
df_ratings=pd.read_csv('data/raw/Ratings.csv')
df_users=pd.read_csv('data/raw/Users.csv')

C:\Users\ks868\AppData\Local\Temp\ipykernel_19052\1519822492.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  df_book=pd.read_csv('data/raw/Books.csv')

In [3]:
df_book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
df_ratings.shape

(1149780, 3)

In [5]:
df_full=pd.merge(df_ratings,df_book,on='ISBN',how='outer')
df_full=pd.merge(df_full,df_users,on='User-ID',how='outer')

In [6]:
df_users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [7]:
df_users.drop(columns='Age',inplace=True)

In [8]:
df_book.drop(columns=['Image-URL-S','Image-URL-M'],inplace=True)

In [9]:
df_book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [10]:
df_full.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Location,Age
0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"nyc, new york, usa",NaN
1,2.0,0195153448,0.0,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,"stockton, california, usa",18.0
2,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"moscow, yukon territory, russia",NaN
3,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"porto, v.n.gaia, portugal",17.0
4,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"farnborough, hants, united kingdom",NaN

In [11]:
df_full=df_full.dropna(subset=['Image-URL-L'])

In [12]:
df_full.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Location,Age
1,2.0,0195153448,0.0,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,"stockton, california, usa",18.0
7,8.0,0002005018,5.0,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"timmins, ontario, canada",NaN
8,8.0,0060973129,0.0,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,"timmins, ontario, canada",NaN
9,8.0,0374157065,0.0,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,"timmins, ontario, canada",NaN
10,8.0,0393045218,0.0,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,"timmins, ontario, canada",NaN

In [13]:
df_full.isnull().sum()

User-ID                  1209
ISBN                        0
Book-Rating              1209
Book-Title                  0
Book-Author                 2
Year-Of-Publication         0
Publisher                   2
Image-URL-S                 0
Image-URL-M                 0
Image-URL-L                 0
Location                 1209
Age                    279042
dtype: int64

In [14]:
df_full.dropna(subset=['User-ID','Book-Rating','Location','Book-Author','Publisher'],inplace=True)

In [15]:
df_full.shape

(1031128, 12)

In [16]:
df_full.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Location,Age
1,2.0,0195153448,0.0,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,"stockton, california, usa",18.0
7,8.0,0002005018,5.0,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"timmins, ontario, canada",NaN
8,8.0,0060973129,0.0,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,"timmins, ontario, canada",NaN
9,8.0,0374157065,0.0,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,"timmins, ontario, canada",NaN
10,8.0,0393045218,0.0,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,"timmins, ontario, canada",NaN

In [17]:
df_full=df_full[df_full['Book-Rating']>0]

In [18]:
df_full.shape

(383837, 12)

In [19]:
df_full.duplicated().sum()

np.int64(0)

In [20]:
df_full.to_csv('data/processed/clean_books.csv', index=False)

In [21]:
df=pd.read_csv("data/processed/clean_books.csv")

In [22]:
df.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Location,Age
0,8.0,0002005018,5.0,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"timmins, ontario, canada",NaN
1,8.0,074322678X,5.0,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,"timmins, ontario, canada",NaN
2,8.0,0887841740,5.0,The Middle Stories,Sheila Heti,2004,House of Anansi Press,http://images.amazon.com/images/P/0887841740.0...,http://images.amazon.com/images/P/0887841740.0...,http://images.amazon.com/images/P/0887841740.0...,"timmins, ontario, canada",NaN
3,8.0,1552041778,5.0,Jane Doe,R. J. Kaiser,1999,Mira Books,http://images.amazon.com/images/P/1552041778.0...,http://images.amazon.com/images/P/1552041778.0...,http://images.amazon.com/images/P/1552041778.0...,"timmins, ontario, canada",NaN
4,8.0,1567407781,6.0,The Witchfinder (Amos Walker Mystery Series),Loren D. Estleman,1998,Brilliance Audio - Trade,http://images.amazon.com/images/P/1567407781.0...,http://images.amazon.com/images/P/1567407781.0...,http://images.amazon.com/images/P/1567407781.0...,"timmins, ontario, canada",NaN

In [23]:
df.columns

Index(['User-ID', 'ISBN', 'Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L', 'Location', 'Age'],
      dtype='str')

In [24]:
df.drop(columns=['Image-URL-S','Image-URL-M','Location','Age'],axis=0,inplace=True)

In [25]:
df.head(1)

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,8.0,0002005018,5.0,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [26]:
for col in df.columns:

    print(df[col].isnull().sum())

0
0
0
0
0
0
0
0

In [27]:
df_users.head()

   User-ID                            Location
0        1                  nyc, new york, usa
1        2           stockton, california, usa
2        3     moscow, yukon territory, russia
3        4           porto, v.n.gaia, portugal
4        5  farnborough, hants, united kingdom

In [28]:
df.shape

(383837, 8)

In [29]:
df['User-ID'].duplicated().sum()

np.int64(315746)

In [30]:
print("Unique value column wise")
for col in df.columns:
    print(df[col].nunique(),col)
print(f"shape of the data : {df.shape}")

Unique value column wise
68091 User-ID
149831 ISBN
10 Book-Rating
135563 Book-Title
62110 Book-Author
105 Year-Of-Publication
11573 Publisher
149711 Image-URL-L
shape of the data : (383837, 8)

In [31]:
df.shape

(383837, 8)

In [32]:
value=df['Book-Title'].value_counts().head(10)
print(value)

Book-Title
The Lovely Bones: A Novel                           707
Wild Animus                                         581
The Da Vinci Code                                   494
The Secret Life of Bees                             406
The Nanny Diaries: A Novel                          393
The Red Tent (Bestselling Backlist)                 383
Bridget Jones's Diary                               377
A Painted House                                     366
Life of Pi                                          336
Harry Potter and the Chamber of Secrets (Book 2)    326
Name: count, dtype: int64

In [33]:
value = df['Book-Title'].value_counts().head(10)
for i in range(0, 10):
    title = value.index[i]
    print(df[df["Book-Title"] == title][['ISBN', 'Book-Rating', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']].head(5))

            ISBN  Book-Rating                 Book-Title   Book-Author  \
484   0316666343         10.0  The Lovely Bones: A Novel  Alice Sebold
633   0316666343          3.0  The Lovely Bones: A Novel  Alice Sebold
993   0316666343          7.0  The Lovely Bones: A Novel  Alice Sebold
1827  0316666343         10.0  The Lovely Bones: A Novel  Alice Sebold
2905  0316666343          9.0  The Lovely Bones: A Novel  Alice Sebold

      Year-Of-Publication      Publisher
484                  2002  Little, Brown
633                  2002  Little, Brown
993                  2002  Little, Brown
1827                 2002  Little, Brown
2905                 2002  Little, Brown
            ISBN  Book-Rating   Book-Title   Book-Author  Year-Of-Publication  \
853   0971880107          2.0  Wild Animus  Rich Shapero                 2004
1392  0971880107          5.0  Wild Animus  Rich Shapero                 2004
1422  0971880107          5.0  Wild Animus  Rich Shapero                 2004
1664  0971880107          1.0  Wild Animus  Rich Shapero                 2004
2732  0971880107          3.0  Wild Animus  Rich Shapero                 2004

     Publisher
853    Too Far
1392   Too Far
1422   Too Far
1664   Too Far
2732   Too Far
            ISBN  Book-Rating         Book-Title Book-Author  \
500   0385504209         10.0  The Da Vinci Code   Dan Brown
814   0385504209         10.0  The Da Vinci Code   Dan Brown
995   0385504209          7.0  The Da Vinci Code   Dan Brown
1121  0385504209          9.0  The Da Vinci Code   Dan Brown
1513  0385504209          7.0  The Da Vinci Code   Dan Brown

      Year-Of-Publication  Publisher
500                  2003  Doubleday
814                  2003  Doubleday
995                  2003  Doubleday
1121                 2003  Doubleday
1513                 2003  Doubleday
            ISBN  Book-Rating               Book-Title    Book-Author  \
158   0142001740          9.0  The Secret Life of Bees  Sue Monk Kidd
393   0142001740         10.0  The Secret Life of Bees  Sue Monk Kidd
992   0142001740         10.0  The Secret Life of Bees  Sue Monk Kidd
2629  0142001740          8.0  The Secret Life of Bees  Sue Monk Kidd
2710  0142001740          6.0  The Secret Life of Bees  Sue Monk Kidd

      Year-Of-Publication      Publisher
158                  2003  Penguin Books
393                  2003  Penguin Books
992                  2003  Penguin Books
2629                 2003  Penguin Books
2710                 2003  Penguin Books
            ISBN  Book-Rating                  Book-Title      Book-Author  \
333   0312278586          6.0  The Nanny Diaries: A Novel  Emma McLaughlin
2328  0312291639          9.0  The Nanny Diaries: A Novel  Emma McLaughlin
3201  0312278586          5.0  The Nanny Diaries: A Novel  Emma McLaughlin
3226  0312278586          5.0  The Nanny Diaries: A Novel  Emma McLaughlin
3616  0312291639          8.0  The Nanny Diaries: A Novel  Emma McLaughlin

      Year-Of-Publication             Publisher
333                  2002    St. Martin's Press
2328                 2003  St. Martin's Griffin
3201                 2002    St. Martin's Press
3226                 2002    St. Martin's Press
3616                 2003  St. Martin's Griffin
            ISBN  Book-Rating                           Book-Title  \
926   0312195516          9.0  The Red Tent (Bestselling Backlist)
1693  0312195516          9.0  The Red Tent (Bestselling Backlist)
2620  0312195516          9.0  The Red Tent (Bestselling Backlist)
6394  0312195516          7.0  The Red Tent (Bestselling Backlist)
7375  0312195516          8.0  The Red Tent (Bestselling Backlist)

        Book-Author  Year-Of-Publication    Publisher
926   Anita Diamant                 1998  Picador USA
1693  Anita Diamant                 1998  Picador USA
2620  Anita Diamant                 1998  Picador USA
6394  Anita Diamant                 1998  Picador USA
7375  Anita Diamant                 1998  Picador USA
            ISBN  Book-Rating             Book-Title     Book-Author  \
4335  014028009X          9.0  Bridget Jones's Diary  Helen Fielding
4691  014028009X          7.0  Bridget Jones's Diary  Helen Fielding
5757  014028009X         10.0  Bridget Jones's Diary  Helen Fielding
7357  014028009X          4.0  Bridget Jones's Diary  Helen Fielding
7365  0141000198          4.0  Bridget Jones's Diary  Helen Fielding

      Year-Of-Publication       Publisher
4335                 1999   Penguin Books
4691                 1999   Penguin Books
5757                 1999   Penguin Books
7357                 1999   Penguin Books
7365                 2001  Penguin Putnam
            ISBN  Book-Rating       Book-Title   Book-Author  \
136   044023722X          7.0  A Painted House  John Grisham
211   044023722X          8.0  A Painted House  John Grisham
1437  044023722X          8.0  A Painted House  John Grisham
3101  044023722X          5.0  A Painted House  John Grisham
8269  044023722X         10.0  A Painted House  John Grisham

      Year-Of-Publication                Publisher
136                  2001  Dell Publishing Company
211                  2001  Dell Publishing Company
1437                 2001  Dell Publishing Company
3101                 2001  Dell Publishing Company
8269                 2001  Dell Publishing Company
            ISBN  Book-Rating  Book-Title  Book-Author  Year-Of-Publication  \
146   0151008116          9.0  Life of Pi  Yann Martel                 2002
744   0156027321          9.0  Life of Pi  Yann Martel                 2003
888   0156027321         10.0  Life of Pi  Yann Martel                 2003
1274  0156027321          9.0  Life of Pi  Yann Martel                 2003
1718  0156027321         10.0  Life of Pi  Yann Martel                 2003

          Publisher
146        Harcourt
744   Harvest Books
888   Harvest Books
1274  Harvest Books
1718  Harvest Books
            ISBN  Book-Rating  \
185   0439064864          9.0
186   0439064872          9.0
1977  0439064864          9.0
5170  0439064864          7.0
5206  0439064872         10.0

                                            Book-Title    Book-Author  \
185   Harry Potter and the Chamber of Secrets (Book 2)  J. K. Rowling
186   Harry Potter and the Chamber of Secrets (Book 2)  J. K. Rowling
1977  Harry Potter and the Chamber of Secrets (Book 2)  J. K. Rowling
5170  Harry Potter and the Chamber of Secrets (Book 2)  J. K. Rowling
5206  Harry Potter and the Chamber of Secrets (Book 2)  J. K. Rowling

      Year-Of-Publication   Publisher
185                  1999  Scholastic
186                  2000  Scholastic
1977                 1999  Scholastic
5170                 1999  Scholastic
5206                 2000  Scholastic

In [34]:
value.head()

Book-Title
The Lovely Bones: A Novel     707
Wild Animus                   581
The Da Vinci Code             494
The Secret Life of Bees       406
The Nanny Diaries: A Novel    393
Name: count, dtype: int64

In [35]:
# Daily streak check - Dataset ready for Pivot Table
print("Dataset shape ready for Pivot Matrix:", df.shape)

Dataset shape ready for Pivot Matrix: (383837, 8)

In [38]:
import pandas as pd
import numpy as np

books = pd.read_csv('data/raw/Books.csv', sep=';', on_bad_lines='skip', encoding="latin-1", low_memory=False)
users = pd.read_csv('data/raw/Users.csv', sep=';', on_bad_lines='skip', encoding="latin-1")
ratings = pd.read_csv('data/raw/Ratings.csv', sep=';', on_bad_lines='skip', encoding="latin-1")